version: "3.0"
services: 
  web:
    image: web-app
    build: 
      context: .
      dockerfile: Dockerfile_compose   # Specify the Dockerfile to use
    ports:
      - "5000:5000"
  redis:
    image: redis
  # mysql:
  #   image: mysql